### ISSUE TITLE
Feat: Add the option to (not) paste after selecting

### ISSUE THREAD

**Issue by MKrabs** [FelipeFTN/Emoji-Copy#29]
Sometimes I select the right emoji but have the cursor on the wrong position, which means the emoji is pasted involontairy after selecting it.

I would love to have an option for the extension to optionally paste the selected emoji 👍

**Comment by FelipeFTN** [comment]
Heyy @MKrabs!! How are you?
Well, I think we already have this feature implemented in Emoji Copy's settings.
**PR I worked on this feature: #25** :tada: 

Take a look at Extension and see Emoji Copy Settings menu, there you can **disable the paste on select** feature!
Take a look, and tell me if it's right, please! :pray:

**Comment by MKrabs** [comment]
Hi,

This is the settings page I see:
![image](https://github.com/FelipeFTN/Emoji-Copy/assets/71791731/4a93af81-ac4a-4c90-947b-8c081bd66a51)

And the version is in fact the latest.
![image](https://github.com/FelipeFTN/Emoji-Copy/assets/71791731/4d35ba17-d1e3-47a2-a241-f84d977c540e)

I saw the setting in the xml about `paste-on-select` ([here](https://github.com/FelipeFTN/Emoji-Copy/blob/master/emoji-copy%40felipeftn/schemas/org.gnome.shell.extensions.emoji-copy.gschema.xml#L28)), and was confused why I don't see any setting about it in the menu..?

**Comment by FelipeFTN** [comment]
**:sweat_smile: So sorry, @MKrabs!**
I was right I added this feature inside Preferences hahaha
**You're right, there is no option like this, I'm adding this right now! :tada:** 
Thank you so much hahaha Latter, I'll link here the pull request :heart:
