### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by PowerSlime** [FelipeFTN/Emoji-Copy#47]
As in the title 😄
Any news about adding Gnome 46 support?

**Comment by FelipeFTN** [comment]
Yess! Working right into it! @PowerSlime :100:

**Comment by FelipeFTN** [comment]
New release going to review, buddy! :rocket:

**Comment by PowerSlime** [comment]
Omg, no way it's that fast! I need to learn some day to contribute to gnome's ecosystem either :smile: 
Waiting for release and prepared for update :wink:
