### ISSUE TITLE
Missing new emojis

### ISSUE THREAD

**Issue by pierrebrd** [FelipeFTN/Emoji-Copy#50]
The extensions works fine, but the emoji list is a bit outdated, it lacks every emoji released from Emoji V12.0 (released in 2019) and Emoji V15.1 (released in 2023). here is a list of emojis added in every version : [https://emojipedia.org/emoji-versions](url)
Could you update the emoji list ? Thanks :)

**Comment by pavinjosdev** [comment]
@pierrebrd Hi 😄

Make sure you're using the latest version of Emoji-Copy (v21) from Gnome Extensions:
https://extensions.gnome.org/extension/6242/emoji-copy/

The latest Unicode 15.1 emojis are supported 🥹
The downside is it's only available for Gnome 45 and 46 🙂‍↕️

**Comment by pierrebrd** [comment]
Okay thank you ! I'm still using Gnome 42 on ubuntu 22.04, i'm going to wait for 24.04 to be a bit more...stable
