### ISSUE TITLE
Warning Emoji wrong after copy

### ISSUE THREAD

**Issue by ItzYanick** [FelipeFTN/emoji-copy#9]
## Bug Report

**Current Behavior**
When clicking the emoji for ⚠️ it returns ⚠.

**Expected behavior/code**
When clicking the emoji for ⚠️ it should return ⚠️.

**Environment**
- emoji-copy version(s): 8
- OS: Fedora 38 (Gnome 44.4)

**Additional context/Screenshots**
I got the other emoji from copying it from a website

**Comment by FelipeFTN** [comment]
Thank you for reporting...
At first look, it seems to be a simple bug, maybe changing the emoji character from the [EmojiCharacter.js](https://github.com/FelipeFTN/emoji-copy/blob/master/emoji-copy%40felipeftn/data/emojisCharacters.js) file would solve it.
I will be taking a look at it soon.

**Comment by FelipeFTN** [comment]
The Issue was fixed on PR #10 and released on version 9 of the extension. Feel free to open new issues for new reports! 👍 Thanks a lot.
